---
# ---------------------------
# Essential packages
# ---------------------------

- name: non-free repos
  apt_repository:
    repo: '{{ item }}'
    state: present
    validate_certs: yes
    update_cache: yes
  with_items:
    - 'deb ftp://ftp.debian.org/debian {{ debian_release }} main contrib non-free'
