#!/usr/bin/env zsh
##################################
# Install pyenv via pyenv-installer locally on $DOT_PATH
##################################

autoload dot_printf_install

pyenv_url=https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer
pyenv_deps=(libssl-dev)

pyenv_install() {
    pyenv install -fv $1
}

#
# Install pyenv
#
dot_printf_install pyenv
sudo apt-get install -y $pyenv_deps
curl -L $pyenv_url | bash

#
# Install many python versions
#
dot_printf_install pythons

# By default, until pyenv is not present,
# its environment variables won't be loaded
# at ~/.zshenv level, therefore, they need to be forced at this point
# to install pythons properly
export PYENV_ROOT="$HOME/.pyenv"
PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# Now, we can install the thing
pyenv_install 2.7.9
pyenv_install 3.2.6
pyenv_install 3.3.6
pyenv_install 3.4.3

# Set systemwide python as default
pyenv global system

