#!/bin/bash

#
OMZSH_HOME=~/.oh-my-zsh

#
# Printing and format options
#

function do_printf {
  OUTPUT_COLOR=$2
  if [ -z $OUTPUT_COLOR ]; then
    OUTPUT_COLOR="\e[96m"
  fi
  printf "* ${OUTPUT_COLOR}$1\e[0m\n"
}

function printf_install {
  do_printf "[+] Install: $1 ..." "\e[1m\e[95m"
}

function printf_uninstall {
  do_printf "[-] Uninstall: $1 ..." "\e[1m\e[31m"
}

function printf_setup {
  do_printf "[.] Setting up: $1 ..."
}

function printf_update {
  do_printf "[*] Update: $1 ..."
}

function printf_clean {
  do_printf "[-] Cleanse: $1 ..."
}

function printf_run {
  do_printf "[\$] Running: $1 ..."
}

function printf_help {
  echo "[?] $1: $2."
}

function printf_err {
  do_printf "[!] Whoops!: $1" "\e[1m\e[31m"
}

function printf_warn {
  do_printf "[!] WARNING: $1" "\e[1m\e[33m"
}

# Install stow
printf_install "GNU stow"
sudo apt-get install -y stow

# Install ZSH
printf_install "zsh"
sudo apt-get install -y zsh

# Install oh-my-zsh
printf_install "on-my-zsh"
rm -rf $OMZSH_HOME
git clone https://github.com/robbyrussell/oh-my-zsh.git $OMZSH_HOME

# Set new shell
printf_setup "chsh -s zsh"
chsh -s $(which zsh)

# Run zsh afterwards
printf_run "zsh"
zsh
