#!/bin/bash

#
OMZSH_HOME=~/.oh-my-zsh
ZSH_HOME=~/.zsh

# Printing and format options
. $ZSH_HOME/lib/printf

# Install stow
printf_install "essential packages"
sudo apt-get install -y stow zsh git build-essential

# Install oh-my-zsh
printf_install "on-my-zsh"
rm -rf $OMZSH_HOME
git clone https://github.com/robbyrussell/oh-my-zsh.git $OMZSH_HOME

# Set new shell
printf_setup "chsh -s zsh"
stow zsh && chsh -s $(which zsh)
printf_warn "Your dotfiles environment has been properly set up. You will need to re-login for the changes to be applied."
