#!/usr/bin/env zsh
##################################
# Install git locally on $DOT_PATH
##################################

autoload dot_printf_install
autoload dot_printf_run
autoload dot_printf_clean

#
# Essential variables
#
git_version=${1:-2.5.3}
git_basename=git-$git_version
git_tarball=$git_basename.tar.xz
git_url=https://www.kernel.org/pub/software/scm/git/$git_tarball

cd /tmp

#
# Get the actual git source tarball
#
dot_printf_run "Getting git tarball"
wget $git_url -O $git_tarball && tar xf $git_tarball
rm -f $git_tarball

#
# Get dependencies
#
dot_printf_install "Git dependencies"
sudo apt-get build-dep -y git

#
# Compile it
#
dot_printf_install "Compile & install git-scm"
cd $git_basename && ./configure --prefix=$DOT_PATH && make install

#
# Remove everything
#
dot_printf_clean everything
cd /tmp && rm -rf $git_basename
