#!/usr/bin/env zsh
##################################
# Install neovim
##################################

autoload dot_printf_install

# The actual variables for vim compilation
nvim_git=https://github.com/neovim/neovim.git
nvim_src=~/Projects/nvim
nvim_deps=(vim-gtk)
nvim_pkgs=(exuberant-ctags)
nvim_sudo_bin=/usr/local/bin/nvim
nvim_cmake_flags="CMAKE_EXTRA_FLAGS=-DCMAKE_INSTALL_PREFIX:PATH=$DOT_PATH"

# First of all, we need some dependencies
dot_printf_install "nvim dependencies"
sudo apt-get install -y "${nvim_pkgs[@]}"
sudo apt-get build-dep -y "${nvim_deps[@]}"

# Now, we do the thing
dot_printf_install "nvim"

# Clone/pull the repo
if [ ! -d $nvim_src ]; then
    git clone $nvim_git $nvim_src
else
    git -C $nvim_src pull
fi

# Compile and install neovim
cd $nvim_src
rm -rf build
make clean
make CMAKE_BUILD_TYPE=Release $nvim_cmake_flags && make install || exit 1

# Symlink vim so it can be available systemwide
dot_printf_install "Symlink to ${nvim_sudo_bin}"
sudo ln -svf $(which nvim) $nvim_sudo_bin

