#!/usr/bin/env zsh
##################################
# Install rclone locally on $GO_PATH
##################################

autoload dot_printf_install

rclone_pkg=github.com/ncw/rclone
#
# Install rclone
#
dot_printf_install "rclone"
if which rclone &> /dev/null; then
    go get -u -v $rclone_pkg
else
    go get -v $rclone_pkg
fi
