#!/usr/bin/env zsh
##################################
# Set up vim-plug and install plugins
##################################

# Vundle-related variables
plug_dir=~/.vim/autoload/plug.vim
plug_src=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

dot_printf_install vim-plug
curl -fLo $plug_dir --create-dirs $plug_src


dot_printf_install "vim plugins"
nvim +PlugInstall +qall
