#!/usr/bin/env zsh
##################################
# Install volnoti
##################################
set -e

autoload dot_printf
autoload dot_printf_install

# The actual variables for volnoti compilation
volnoti_git=https://github.com/hcchu/volnoti.git
volnoti_src=~/Projects/volnoti

# Now, we do the thing
dot_printf_install "volnoti"

# Clone/pull the repo
dot_printf "clone volnoti git repository"
if [ ! -d $volnoti_src ]; then
    git clone  $volnoti_git $volnoti_src
else
    git -C $volnoti_src pull
fi

# Compile and install volnoti
dot_printf "compile and install volnoti"
cd $volnoti_src
[ ! -x configure ] && ./prepare.sh
./configure --prefix=$DOT_PATH && make clean && make && make install

