---
# ---------------------------
# Essential packages
# ---------------------------

# Make sure the minimum
# necessary packages are installed

- name: Absolute essentials
  apt: pkg={{ item }} state=latest
  with_items:
    - stow
    - symlinks
    - socat
    - openssh-client
    - software-properties-common

- name: General administration utilities
  apt: pkg={{ item }} state=latest
  with_items:
      - dnsutils
      - whois
      - findutils
      - locate

- name: Codecs
  apt: pkg={{ item }} state=latest
  with_items:
      - tar
      - zip
      - unzip
      - unrar

- name: openvpn
  apt: pkg={{ item }} state=latest
  with_items:
    - openvpn

- name: zsh
  apt: pkg={{ item }} state=latest
  with_items:
    - zsh

- name: ntp
  apt: pkg={{ item }} state=latest
  with_items:
    - ntp

- name: ruby
  apt: pkg={{ item }} state=latest
  with_items:
    - ruby

- name: file systems utilities
  apt: pkg={{ item }} state=latest
  with_items:
      - parted
      - hfsprogs
      - exfat-utils
      - dosfstools

- name: Utilities for monitoring processes
  apt: pkg={{ item }} state=latest
  with_items:
    - htop
    - sysstat
    - iotop

- name: pip
  easy_install:
    name: pip

- name: python
  apt: pkg={{ item }} state=latest
  with_items:
      - python
      - python3
      - python3-pip
      - python3-venv

- name: networking tools
  apt: pkg={{ item }} state=latest
  with_items:
    - iputils-tracepath
    - iputils-ping
    - nethogs
    - tcpdump
    - iftop
    - iptraf
    - netcat
    - nmap
    - telnet

- name: HTTP utilities
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - wget
    - httpie

- name: android tools
  apt: pkg={{ item }} state=latest
  with_items:
      - android-tools-adb
      - android-tools-fastboot
      - android-tools-fsutils
