---
# ---------------------------
# Essential packages
# ---------------------------
# This role makes sure the minimum
# necessary packages are installed

- name: Set up essential packages (APT)
  apt: pkg={{ item }} state=latest
  with_items:
    - lightdm
    - i3
    - ranger
    - curl
    - htop
    - irssi
    - links
    - tcpdump
    - sysstat
    - nethogs
    - colortest
    - curl
    - wget
    - mc
