---
# ---------------------------
# Essential packages
# ---------------------------
# This role makes sure the minimum
# necessary packages are installed

- name: Set up essential packages (APT)
  apt: pkg={{ item }} state=latest
  with_items:
    - xorg
    - lightdm
    - mesa-utils
    - i3
    - ranger
    - curl
    - htop
    - irssi
    - links
    - tcpdump
    - sysstat
    - nethogs
    - colortest
    - curl
    - wget
    - chromium

- name: Purge undesired packages
  apt: pkg={{ item }} state=absent
  with_items:
    - mc
