---
# ---------------------------
# Essential packages
# ---------------------------

# Make sure the minimum
# necessary packages are installed

- name: Essential packages
  apt: pkg={{ item }} state=latest
  with_items:

      # Absolute essentials
    - xorg
    - lightdm
    - i3 # our beloved and minimalistic window manager
    - colortest # For testing color on terminals
    - openssh-client
      # Audio support
    - pulseaudio
    - pavucontrol
    - alsa-utils

- name: Utilities for monitoring processes
  apt: pkg={{ item }} state=latest
  with_items:
    - htop
    - sysstat

- name: Utilities for network debugging
  apt: pkg={{ item }} state=latest
  with_items:
    - nethogs
    - tcpdump
    - iftop
    - iptraf
    - netcat
    - nmap

- name: HTTP utilities
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - wget
    - httpie

- name: User apps
  apt: pkg={{ item }} state=latest
  with_items:
      # Our beloved web browsers
    - links
    - chromium

      # Userland apps
    - irssi # IRC client
    - mesa-utils # utilities for GL
    - zathura # PDF reader
    - lxappearance # For setting up GTK
    - gpicview # pictures viewer
    - cmus # my music player
    - smplayer # my video player

      # Our beloved file manager
    - ranger

      # Wallpaper setter
    - nitrogen

      # torrents are awesome
    - transmission-gtk

# Make sure the minimum
# necessary packages are uninstalled

- name: Purge undesired packages
  apt: pkg={{ item }} state=absent
  with_items:
    - mc # midnight commander

- name: GTK+ engines
  apt: pkg={{ item }} state=latest
  with_items:
      - gtk2-engines-murrine
