---
# ---------------------------
# Essential packages
# ---------------------------

# Make sure the minimum
# necessary packages are uninstalled

- name: Purge undesired packages
  apt: pkg={{ item }} state=absent
  with_items:
    - python-pip

# Make sure the minimum
# necessary packages are installed

- name: Essential packages
  apt: pkg={{ item }} state=latest
  with_items:

    # Absolute essentials
    - apt-transport-https
    - symlinks

    # X11
    - xorg
    - xautolock
    - xutils
    - xclip
    - xsel
    - rxvt-unicode-256color # my beloved terminal emulator
    - lightdm
    - i3 # our beloved and minimalistic window manager
    - compton # compositor
    - colortest # For testing color on terminals
    - scrot # screenshots
    - openssh-client
    - libnotify-bin
    - inotify-tools

      # Audio support
    - pulseaudio
    - pavucontrol
    - alsa-utils

- name: General administration utilities
  apt: pkg={{ item }} state=latest
  with_items:
      - dnsutils
      - whois
      - findutils
      - locate
      - unzip
      - unrar

- name: file systems utilities
  apt: pkg={{ item }} state=latest
  with_items:
      - parted
      - gparted
      - hfsprogs
      - exfat-utils


- name: Utilities for monitoring processes
  apt: pkg={{ item }} state=latest
  with_items:
    - htop
    - sysstat
    - iotop

- name: pip
  easy_install:
    name: pip

- name: python
  apt: pkg={{ item }} state=latest
  with_items:
      - python
      - python3
      - python3-pip

- name: i3pystatus
  pip:
      name: '{{ item }}'
      state: latest
      executable: pip3
  with_items:
      - i3pystatus
      - netifaces
      - psutil
      - colour

- name: system-wide fonts
  apt: pkg={{ item }} state=latest
  with_items:
      - fonts-liberation
      - fonts-droid

- name: Utilities for network debugging
  apt: pkg={{ item }} state=latest
  with_items:
    - iputils-tracepath
    - iputils-ping
    - nethogs
    - tcpdump
    - iftop
    - iptraf
    - netcat
    - nmap
    - telnet

- name: HTTP utilities
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - wget
    - httpie

- name: android tools
  apt: pkg={{ item }} state=latest
  with_items:
      - android-tools-adb
      - android-tools-fastboot
      - android-tools-fsutils

- name: development tools
  apt: pkg={{ item }} state=latest
  with_items:
      - build-essential
      - bc
      - automake
      - autoconf
      - pkg-config
      - mercurial
      - cmake-curses-gui
      - gdb
      - cgdb

- name: User apps
  apt: pkg={{ item }} state=latest
  with_items:
      # Our beloved web browsers
    - links
    - chromium

      # Userland apps
    - irssi # IRC client
    - mesa-utils # utilities for GL
    - zathura # PDF reader
    - lxappearance # For setting up GTK
    - gpicview # pictures viewer
    - gimp # Image editor
    - cmus # my music player
    - smplayer # my video player
    - pepperflashplugin-nonfree # flash player
    - shutter # advanced screenshots

      # Our beloved file manager
    - ranger

      # Wallpaper setter
    - nitrogen

      # torrents are awesome
    - transmission-gtk


- name: keepass2
  apt: pkg={{ item }} state=latest
  with_items:
    - keepass2 # password manager
    - mono-complete

- name: GTK+ engines
  apt: pkg={{ item }} state=latest
  with_items:
      - gtk2-engines-murrine
