---
# ---------------------------
# Essential packages
# ---------------------------

# Make sure the minimum
# necessary packages are uninstalled

- name: Purge undesired packages
  apt: pkg={{ item }} state=absent
  with_items:
    - python-pip

# Make sure the minimum
# necessary packages are installed

- name: Absolute essentials
  apt: pkg={{ item }} state=latest
  with_items:
    - apt-transport-https
    - software-properties-common  # apt-add-repository
    - stow
    - symlinks
    - socat
    - openssh-client

- name: Sound support
  apt: pkg={{ item }} state=latest
  with_items:
      # Audio support
    - pulseaudio
    - pavucontrol
    - sox # audio utilities
    - alsa-utils

- name: General administration utilities
  apt: pkg={{ item }} state=latest
  with_items:
      - dnsutils
      - whois
      - findutils
      - locate

- name: Codecs
  apt: pkg={{ item }} state=latest
  with_items:
      - tar
      - zip
      - unzip
      - unrar

- name: openvpn
  apt: pkg={{ item }} state=latest
  with_items:
    - openvpn

- name: zsh
  apt: pkg={{ item }} state=latest
  with_items:
    - zsh

- name: ntp
  apt: pkg={{ item }} state=latest
  with_items:
    - ntp

- name: ruby
  apt: pkg={{ item }} state=latest
  with_items:
    - ruby

- name: file systems utilities
  apt: pkg={{ item }} state=latest
  with_items:
      - parted
      - hfsprogs
      - exfat-utils
      - dosfstools

- name: Utilities for monitoring processes
  apt: pkg={{ item }} state=latest
  with_items:
    - htop
    - sysstat
    - iotop

- name: pip
  easy_install:
    name: pip

- name: python
  apt: pkg={{ item }} state=latest
  with_items:
      - python
      - python3
      - python3-pip
      - python3-venv

- name: networking tools
  apt: pkg={{ item }} state=latest
  with_items:
    # network management
    - wicd
    - wicd-curses

    # network diagnostic tools
    - iputils-tracepath
    - iputils-ping
    - nethogs
    - tcpdump
    - iftop
    - iptraf
    - netcat
    - nmap
    - telnet

- name: HTTP utilities
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - wget
    - httpie

- name: android tools
  apt: pkg={{ item }} state=latest
  with_items:
      - android-tools-adb
      - android-tools-fastboot
      - android-tools-fsutils

- name: printers and scanners
  apt: pkg={{ item }} state=latest
  with_items:
    - cups
    - hplip # HP printers and scanners support

- name: bluetooth support
  apt: pkg={{ item }} state=latest
  with_items:
    - bluez
    - bluez-tools
    - btscanner

- name: power saving tools (for laptops)
  apt:
    pkg: '{{ item }}'
    state: latest
  with_items:
    - laptop-mode-tools
    - powerstat
    - powertop
