---
# ---------------------------
# Essential packages
# ---------------------------

# Make sure the minimum
# necessary packages are installed

- name: Essential packages
  apt: pkg={{ item }} state=latest
  with_items:

    # Absolute essentials
    - apt-transport-https
    - xorg
    - cmake-curses-gui

    # ""arbitraty precision calculator language""
    # I just use it for compiling linux
    - bc
    - xautolock
    - lightdm
    - i3 # our beloved and minimalistic window manager
    - compton # compositor
    - colortest # For testing color on terminals
    - scrot # screenshots
    - openssh-client
    - libnotify-bin
    - inotify-tools
      # Audio support
    - pulseaudio
    - pavucontrol
    - alsa-utils

- name: General administration utilities
  apt: pkg={{ item }} state=latest
  with_items:
      - dnsutils
      - findutils
      - locate
      - unzip
      - unrar

- name: file systems utilities
  apt: pkg={{ item }} state=latest
  with_items:
      - hfsprogs
      - exfat-utils


- name: Utilities for monitoring processes
  apt: pkg={{ item }} state=latest
  with_items:
    - htop
    - sysstat
    - iotop

- name: python
  apt: pkg={{ item }} state=latest
  with_items:
      - python
      - python-pip
      - python3
      - python3-pip

- name: i3pystatus
  pip:
      name: '{{ item }}'
      state: latest
      executable: pip3
  with_items:
      - i3pystatus
      - netifaces
      - psutil
      - colour

- name: system-wide fonts
  apt: pkg={{ item }} state=latest
  with_items:
      - fonts-liberation
      - fonts-droid

- name: Utilities for network debugging
  apt: pkg={{ item }} state=latest
  with_items:
    - nethogs
    - tcpdump
    - iftop
    - iptraf
    - netcat
    - nmap
    - telnet

- name: HTTP utilities
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - wget
    - httpie

- name: golang
  apt: pkg={{ item }} state=latest
  with_items:
      - golang

- name: android tools
  apt: pkg={{ item }} state=latest
  with_items:
      - android-tools-adb
      - android-tools-fastboot
      - android-tools-fsutils

- name: User apps
  apt: pkg={{ item }} state=latest
  with_items:
      # Our beloved web browsers
    - links
    - chromium

      # Userland apps
    - irssi # IRC client
    - mesa-utils # utilities for GL
    - zathura # PDF reader
    - lxappearance # For setting up GTK
    - gpicview # pictures viewer
    - gimp # Image editor
    - cmus # my music player
    - smplayer # my video player
    - pepperflashplugin-nonfree # flash player
    - keepass2 # password manager

      # Our beloved file manager
    - ranger

      # Wallpaper setter
    - nitrogen

      # torrents are awesome
    - transmission-gtk

# Make sure the minimum
# necessary packages are uninstalled

- name: Purge undesired packages
  apt: pkg={{ item }} state=absent
  with_items:
    - mc # midnight commander

- name: GTK+ engines
  apt: pkg={{ item }} state=latest
  with_items:
      - gtk2-engines-murrine
