---
# ---------------------------
# docker configuration
# ---------------------------

- name: set up APT key
  apt_key:
      keyserver: pgp.mit.edu
      id: 58118E89F3A912897C070ADBF76221572C52609D

- name: set up repositories
  apt_repository:
      repo: 'deb https://apt.dockerproject.org/repo debian-{{ debian_release }} main'
      state: present

- name: install docker
  apt:
      update_cache: yes
      name: docker-engine
      state: latest

- name: set up non-root access
  user:
      append: yes
      name: '{{ user_name }}'
      groups: docker
