#!/usr/bin/env zsh
###############################
# rclone backup to google drive
###############################

# The actual rclone invocation
for rclone_entry in $(echo $RCLONE_PATH | tr ':' ' ')
do
    # For each entry, get source and destination directory
    src=$(echo $rclone_entry | cut -d@ -f1)
    dest=$(echo $rclone_entry | cut -d@ -f2)

    # send the actual notification
    if [[ ! -z "$DISPLAY" ]]; then
        notify-send --urgency=low "rclone" "Backing up: $src -> $dest"
    fi

    # and then, do the thing
    rclone copy $src "gdrive:$dest" --bwlimit=64

    # send the actual notification
    if [[ ! -z "$DISPLAY" ]]; then
        notify-send --urgency=normal "rclone" "Succesful backup: $src -> $dest"
    fi
done
unset rclone_entry
