#!/usr/bin/env zsh
#############################
# rclone backup to google drive
#############################

# The actual rclone invocation
for rclone_entry in $(echo $RCLONE_PATH | tr ':' ' ')
do
    # For each entry, get source and destination directory
    src=$(echo $rclone_entry | cut -d@ -f1)
    dest=$(echo $rclone_entry | cut -d@ -f2)

    # and then, do the thing
    rclone copy $src "gdrive:$dest" --bwlimit=64
done
unset rclone_entry
