---
#########################################
# ansible main playbook for this machine
#########################################


# Apply common configuration to host
- hosts: 127.0.0.1
  vars:
      user_name: axltxl
      debian_release: stretch

      #######################
      # openssh configuration
      #######################
      # Protocol version
      ssh_protocol: '2'

      # What ports, IPs and protocols we listen for
      ssh_port:
        - 50222

      # Authentication
      ssh_permit_root_login: 'no'
      ssh_pubkey_authentication: 'yes'

      # Change to no to disable tunnelled clear text passwords
      ssh_password_authentication: 'no'

      ##################
      # i3 configuration
      ##################

      # virtualenv for i3pystatus
      i3_venv: '{{ i3_base }}/pystatus'

  sudo: yes
  roles:
      - essentials
      - desktop
      - synaptics
      - i3wm
      - dev
      - openssh
      - rclone
      - spotify
      - syncthing
      - docker
