---
#########################################
# ansible main playbook for this machine
#########################################


# Apply common configuration to host
- hosts: 127.0.0.1
  vars:
      # dotdeb configuration
      dotdeb_repo_version: jessie
      dotdeb_extra_repo: False
  sudo: yes
  roles:
      - apt
      - dotdeb
      - essentials
      - rclone
