---
#########################################
# ansible main playbook for this machine
#########################################


# Apply common configuration to host
- hosts: 127.0.0.1
  vars:
      user_name: axltxl
  sudo: yes
  roles:
      - essentials
      - desktop
      - dev
      - rclone
      - spotify
      - syncthing
