---
#########################################
# ansible main playbook for this machine
#########################################


# Apply common configuration to host
- hosts: 127.0.0.1
  vars:
      user_name: axltxl
      debian_release: stretch

      #######################
      # openssh configuration
      #######################
      # Protocol version
      ssh_protocol: '2'

      # What ports, IPs and protocols we listen for
      ssh_port:
        - 50222

      # Authentication
      ssh_permit_root_login: 'no'
      ssh_pubkey_authentication: 'yes'

      # Change to no to disable tunnelled clear text passwords
      ssh_password_authentication: 'no'

      # Kerberos options
      opensshd_KerberosAuthentication: 'no'
      opensshd_AuthorizedKeysFile: .ssh/authorized_keys

      # Don't read the user's ~/.rhosts and ~/.shosts files
      opensshd_IgnoreRhosts: 'yes'

      # Uncomment if you don't trust ~/.ssh/known_hosts for RhostsRSAAuthentication
      opensshd_IgnoreUserKnownHosts: 'no'

      opensshd_X11Forwarding: 'no'
      opensshd_PrintMotd: 'no'
      opensshd_PrintLastLog: 'yes'
      opensshd_TCPKeepAlive: 'yes'
      opensshd_UseDNS: "no"

      # Set this to 'yes' to enable PAM authentication, account processing,
      # and session processing. If this is enabled, PAM authentication will
      # be allowed through the ChallengeResponseAuthentication and
      # PasswordAuthentication.  Depending on your PAM configuration,
      # PAM authentication via ChallengeResponseAuthentication may bypass
      # the setting of "PermitRootLogin without-password".
      # If you just want the PAM account and session checks to run without
      # PAM authentication, then enable this but set PasswordAuthentication
      # and ChallengeResponseAuthentication to 'no'.
      opensshd_UsePAM: 'yes'

      # i3 home directory
      i3_base: '/home/{{ user_name }}/.i3'

      # virtualenv for i3pystatus
      i3_venv: '{{ i3_base }}/pystatus'

  sudo: yes
  roles:
      - essentials
      - desktop
      - synaptics
      - i3wm
      - dev
      - openssh
      - rclone
      - spotify
      - syncthing
      - docker
